Repository SU-SWS/ace-gryphon, pull requests merged in 2023-09, with the labels that each got.

#54 Added test
  .circleci/config.yml
  .github/auto-label.json
  .github/workflows/label.yml
  .github/workflows/tests.yml
  blt/blt.yml
  blt/ci.blt.yml
  blt/src/Blt/Plugin/Commands/CiCommands.php
  blt/src/Blt/Plugin/Commands/GryphonAcquiaApiCommands.php
  docroot/sites/settings/ci.settings.php
  docroot/sites/settings/config.settings.php
  docroot/sites/settings/fast404.settings.php
  docroot/sites/settings/global.settings.php
  tests/codeception.dist.yml
Labels: size/m

#55 Update to samlauth
  .github/workflows/tests.yml
  blt/blt.yml
  composer.json
  composer.lock
  docroot/sites/settings/default.local.settings.php
  docroot/sites/settings/global.settings.php
  docroot/sites/settings/saml.settings.php
  docroot/sites/settings/simplesamlphp.settings.php
Labels: size/m

#56 samlauth update
  .github/workflows/tests.yml
  blt/blt.yml
  composer.json
  composer.lock
  docroot/sites/settings/default.local.settings.php
  docroot/sites/settings/global.settings.php
  docroot/sites/settings/saml.settings.php
  docroot/sites/settings/simplesamlphp.settings.php
Labels: size/l

#59 DEVOPS-000: Add ddev configuration for local environments
  .ddev/config.yaml
  .gitignore
Labels: size/s
